#!/bin/sh

main() {
    parse_opts "$@"

    dir=~/.local/share/magickshot/Screenshots
    title="$(date +'%Y-%m-%d_%R:%S')"
    dir2=$dir/import-$title.png
    mon="$(randr | cut -d ' ' -f 3)"

    if [ -n "$help" ]; then
	help
    elif [ -n "$selection" ]; then
	screenshot
    elif [ -n "$window" ]; then
	if [ -n "$2" ]; then
	    screenshot -window "$2"
	else
	    screenshot -window $(xdotool getwindowfocus)
	fi
    elif [ -n "$monitor" ]; then
	screenshot -window root && magick -extract $mon $dir2 $dir2
    elif [ -n "$display" ]; then
	screenshot -window root
    elif [ $# -eq 0 ]; then
	screenshot -window root && magick -extract $mon $dir2 $dir2
    else
	help
    fi
}

pl() {
    [ -z $PLAYER ] && PLAYER="mpv"
    setsid $PLAYER --really-quiet --pause=no --keep-open=no "$@" &>/dev/null
}

sound() {
    sound_dir=/usr/share/sounds/deepin/stereo

    if [ -d $sound_dir ]; then
	sound_1=$sound_dir/camera-shutter.wav
	sound_2=$sound_dir/dialog-error.wav

	pl $sound_1 || pl $sound_2
    fi
}

screenshot() {
    [ "$(pidof unclutter xbanish | wc -l)" -ge 1 ] && xdotool mousemove_relative 1 0 ; import "$@" $dir2 && sound
}

randr() {
    xrandr | grep ' connected' | sed 's/ primary//g' | tail -$(expr $(printmon) + 1) | head -1
}

help() {
    printf "Usage:	magickshot [options]

Options:
 -s|--selection │ Take a screenshot of the selection
 -w|--window    │ Take a screenshot of the specified window (default is root)
 -h|--help	│ Print this help message and exit

Use both the selection and window arguments at the same time and you will be able to use the cursor to select a specific window to take a screenshot of.
\n"
}

parse_opts() {
    while [ $# -gt 0 ]; do
        key="$1"
	case $key in
	-h|--help)
	    help=1
	    shift
	    ;;
	-s|--selection)
	    selection=1
	    shift
	    ;;
	-w|--window)
	    window=1
	    shift
	    ;;
	-m|--monitor)
	    monitor=1
	    shift
	    ;;
	-d|--display)
	    display=1
	    shift
	    ;;
        *)
            shift
            ;;
        esac
    done
}

main "$@"
