#!/bin/sh

dir=~/.local/share/imagemagick/Screenshots
title="$(date +'%Y-%m-%d_%R:%S')"
dir2=$dir/import-root-$title.png
sound_dir=/usr/share/sounds/deepin/stereo
sound_1=$sound_dir/camera-shutter.wav
sound_2=$sound_dir/dialog-error.wav

if [ "$1" = "--select" -o "$1" = "-s" ]; then
    if [ "$(pidof unclutter | wc -l)" -ge 1 ]; then
	xdotool mousemove_relative 1 0 && import $dir2 && pl $sound_1 || pl $sound_2
    else
	import $dir2 && pl $sound_1 || pl $sound_2
    fi
elif [ "$1" = "--root" -o "$1" = "-r" ]; then
    if [ -n "$2" ]; then
        import -window "$2" $dir2 && pl $sound_1 || pl $sound_2
    else
        import -window root $dir2 && pl $sound_1 || pl $sound_2
    fi
else
    import -window root $dir2 && pl $sound_1 || pl $sound_2
fi
